spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      username: rootadmin
      password: password
      authentication-database: admin

server:
  port: 8080